### ISSUE TITLE
Exporting Document without Chapters

### ISSUE THREAD

**Issue by GeekTeaa** [xeals/emacs-org-dnd#3]
I love the package, but I often am making documents that do not have any order (like when I'm making a magic item), or when I'm planning out a session (where 'chapters' don't make any sense). Is it possible to export the document without the chapter in the headline, and without the page numbers at the bottom?

**Comment by lhernanz** [comment]
Hi @GeekTeaa, I am updating this code to support the last version of the LaTex template. One of the new features is the support for a dndarticle class that is lighter than the others, not supporting chapters at all. Maybe this is aligned to what you were looking for.

You can have a look at an example here: https://github.com/lhernanz/emacs-org-dnd/blob/master/example/article.pdf

**Comment by GeekTeaa** [comment]
I wrote this issue 2.5 years ago... And you took the time to both provide a solution and reply to my issue on the original repository? 

I love the internet.

Yes, thank you for a fix, I'm excited to make use of it.
